# ─── DESARROLLO LOCAL ───────────────────────────────────────────
# Usa PostgreSQL local (el mismo que tenés corriendo)
spring.datasource.url=jdbc:postgresql://localhost:5432/sofiacouture
spring.datasource.username=postgres
spring.datasource.password=VictorSdef/17
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Hibernate crea/actualiza tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Logs más detallados en dev
logging.level.com.tiendaropa=DEBUG
logging.level.org.springframework.web=INFO

# Payphone (pruebas)
payphone.token=${PAYPHONE_TOKEN:Bearer 10rHXcnfWw0ocIT-4uBu-37LfusBCX30MlMmXpp92PeORGvG7LC5LrDOfS_LHyB4MI2If-NR3gPH01gDeJMdbHNQDVbIn__wTj6ICKbGW-qhd_LHumoDo59GA8mFJGBjufsnGuhP2DUwuWHkrg6Sepy5oRGNGOPHDJ9Be9wvyPybLUHue24FEp7txM9kiarRJ2ndWbeHEm_CcDMncM4fiTpD46eyHeHdBIH1HMsZX2ZFN5GV_o1BpELIqrcy86WYhF4N5pV2aEzXBDEq7zSlG7fUTMCBUpaBQOXU2jeXeACzqTe-590N8Lq2wLQILtLAYxjhKtQkZXzPan1c0EdiiPo9HJA}
payphone.store-id=${PAYPHONE_STORE_ID:df1a133a-bc5c-42ee-b1d3-295a23f021bc}
payphone.response-base-url=${PAYPHONE_RESPONSE_BASE_URL:http://localhost:5173}
