# ─── DESARROLLO LOCAL ───────────────────────────────────────────
# Prioriza variables de Docker/local y si no existen usa fallback local
spring.datasource.url=${DB_URL:${DEV_DB_URL:jdbc:postgresql://localhost:5432/sofiacouture}}
spring.datasource.username=${DB_USERNAME:${DEV_DB_USERNAME:postgres}}
spring.datasource.password=${DB_PASSWORD:${DEV_DB_PASSWORD:VictorSdef/17}}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Hibernate crea/actualiza tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Logs más detallados en dev
logging.level.com.tiendaropa=DEBUG
logging.level.org.springframework.web=INFO

# Payphone (pruebas)
# IMPORTANTE: Pon aqui tus credenciales reales para probar en dev
payphone.token=${PAYPHONE_TOKEN:Bearer W1vyttFVJgsSZBdiBqpL1APz7AgWgJxtBgOIs9yHAJlQMZoWsc9exjZvELks5KM9LQU7wqfDDuUUO40WEDpNrcvcVSdJ3Q6MBF5Oxk5f_ay16me3a413comAJNJCEEzfT1GYuFQwUYBdFGdH-xo3HDnTirj4qUJ3mDZ4Kol8xLizV74n85SYGOSJGXo_jtu_OtbWq85h2M-un9rcDmlukD0pE4IKYAC3Ko-qXkrrnWfr392_Dq3fzWBpjhjDcCbeOnZAQYv8pTEvb6E0xKZ7K5tfvJd58elIYDCuWpArLkLD5Q3lW6l4pReuExpO1i7Hp-pjjAghZQ_XvPNmk-BW8ZNXcWo}
payphone.store-id=${PAYPHONE_STORE_ID:df1a133a-bc5c-42ee-b1d3-295a23f021bc}
payphone.response-base-url=${PAYPHONE_RESPONSE_BASE_URL:http://localhost:5173}
